import {
  UserEntity,
  RoleAssignmentEntity,
  PropertyEntity,
  TenantEntity,
  PaymentEntity,
  ExpenseEntity,
  MaintenanceEntity,
  ServiceProviderEntity,
  AuditEventEntity,
  NotificationEntity,
  RecurringTask,
  UserRoleKey,
  MonthlyPaymentStatusEntity,
} from '../types';

export const INITIAL_PROPERTIES: PropertyEntity[] = [
  {
    id: 'prop-1',
    ownerUserId: 'user-landlord-1',
    name: 'Kampala Apartments',
    location: 'Plot 42 Ntinda-Nakawa Road, Kampala',
    totalUnits: 12,
    currency: 'UGX',
    syncStatus: 'SYNCED',
    lastSyncedAt: Date.now() - 3600000,
    createdAt: Date.now() - 30 * 86400000,
  },
  {
    id: 'prop-2',
    ownerUserId: 'user-landlord-1',
    name: 'Entebbe Heights',
    location: 'Kitubulu, Entebbe Road',
    totalUnits: 8,
    currency: 'UGX',
    syncStatus: 'SYNCED',
    lastSyncedAt: Date.now() - 7200000,
    createdAt: Date.now() - 45 * 86400000,
  },
  {
    id: 'prop-3',
    ownerUserId: 'user-landlord-1',
    name: 'Jinja View Residencies',
    location: 'Main Street, Jinja City',
    totalUnits: 6,
    currency: 'UGX',
    syncStatus: 'SYNCED',
    lastSyncedAt: Date.now() - 10800000,
    createdAt: Date.now() - 60 * 86400000,
  },
];

export const INITIAL_TENANTS: TenantEntity[] = [
  {
    id: 'ten-1',
    userId: 'user-ten-1',
    propertyId: 'prop-1',
    unitId: 'unit-101',
    name: 'John Mukasa',
    phone: '0772123456',
    unitName: 'Unit 101',
    propertyName: 'Kampala Apartments',
    monthlyRent: 1200000,
    rentDue: 1200000,
    arrears: 0,
    advanceCredit: 0,
    paymentStatus: 'Paid',
    leaseStart: Date.now() - 180 * 86400000,
    leaseEnd: Date.now() + 185 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 180 * 86400000,
  },
  {
    id: 'ten-2',
    userId: 'user-ten-2',
    propertyId: 'prop-1',
    unitId: 'unit-102',
    name: 'Sarah Namubiru',
    phone: '0788765432',
    unitName: 'Unit 102',
    propertyName: 'Kampala Apartments',
    monthlyRent: 1200000,
    rentDue: 2400000,
    arrears: 1200000,
    advanceCredit: 0,
    paymentStatus: 'Overdue',
    leaseStart: Date.now() - 120 * 86400000,
    leaseEnd: Date.now() + 245 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 120 * 86400000,
  },
  {
    id: 'ten-3',
    userId: 'user-ten-3',
    propertyId: 'prop-2',
    unitId: 'unit-201',
    name: 'David Ochieng',
    phone: '0701234567',
    unitName: 'Unit 201',
    propertyName: 'Entebbe Heights',
    monthlyRent: 1800000,
    rentDue: 2700000,
    arrears: 900000,
    advanceCredit: 0,
    paymentStatus: 'Overdue',
    leaseStart: Date.now() - 90 * 86400000,
    leaseEnd: Date.now() + 275 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: 'ten-4',
    userId: 'user-ten-4',
    propertyId: 'prop-3',
    unitId: 'unit-301',
    name: 'Grace Akello',
    phone: '0752987654',
    unitName: 'Unit 301',
    propertyName: 'Jinja View Residencies',
    monthlyRent: 1500000,
    rentDue: 1500000,
    arrears: 0,
    advanceCredit: 300000,
    paymentStatus: 'Paid',
    leaseStart: Date.now() - 200 * 86400000,
    leaseEnd: Date.now() + 165 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 200 * 86400000,
  },
  {
    id: 'ten-5',
    userId: 'user-ten-5',
    propertyId: 'prop-1',
    unitId: 'unit-104',
    name: 'Brian Kintu',
    phone: '0779998877',
    unitName: 'Unit 104',
    propertyName: 'Kampala Apartments',
    monthlyRent: 1200000,
    rentDue: 1800000,
    arrears: 600000,
    advanceCredit: 0,
    paymentStatus: 'Overdue',
    leaseStart: Date.now() - 60 * 86400000,
    leaseEnd: Date.now() + 305 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 60 * 86400000,
  },
  {
    id: 'ten-6',
    userId: 'user-ten-6',
    propertyId: 'prop-2',
    unitId: 'unit-202',
    name: 'Patricia Nalwanga',
    phone: '0782334455',
    unitName: 'Unit 202',
    propertyName: 'Entebbe Heights',
    monthlyRent: 1800000,
    rentDue: 1800000,
    arrears: 0,
    advanceCredit: 0,
    paymentStatus: 'Paid',
    leaseStart: Date.now() - 150 * 86400000,
    leaseEnd: Date.now() + 215 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 150 * 86400000,
  },
];

export const INITIAL_PAYMENTS: PaymentEntity[] = [
  {
    id: 'pay-001',
    tenantId: 'ten-1',
    propertyId: 'prop-1',
    unitId: 'unit-101',
    tenantName: 'John Mukasa',
    unitName: 'Unit 101',
    propertyName: 'Kampala Apartments',
    amount: 1200000,
    currency: 'UGX',
    paymentMethod: 'Mobile Money (MTN)',
    paymentStatus: 'SUCCESSFUL',
    externalReference: 'MTN-UG-9823145',
    receiptNumber: 'MARS-RCT-884921',
    recordedBy: 'Peter Ssekandi (Caretaker)',
    notes: 'August 2026 Rent - Full settlement via MTN MoMo',
    date: '2026-08-02',
    paymentTimestamp: Date.now() - 5 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 5 * 86400000,
  },
  {
    id: 'pay-002',
    tenantId: 'ten-4',
    propertyId: 'prop-3',
    unitId: 'unit-301',
    tenantName: 'Grace Akello',
    unitName: 'Unit 301',
    propertyName: 'Jinja View Residencies',
    amount: 1800000,
    currency: 'UGX',
    paymentMethod: 'Mobile Money (Airtel)',
    paymentStatus: 'SUCCESSFUL',
    externalReference: 'AIR-UG-4412099',
    receiptNumber: 'MARS-RCT-884922',
    recordedBy: 'Peter Ssekandi (Caretaker)',
    notes: 'Rent + Advance deposit UGX 300,000 credit',
    date: '2026-08-04',
    paymentTimestamp: Date.now() - 3 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'pay-003',
    tenantId: 'ten-6',
    propertyId: 'prop-2',
    unitId: 'unit-202',
    tenantName: 'Patricia Nalwanga',
    unitName: 'Unit 202',
    propertyName: 'Entebbe Heights',
    amount: 1800000,
    currency: 'UGX',
    paymentMethod: 'Bank Transfer (Stanbic)',
    paymentStatus: 'SUCCESSFUL',
    externalReference: 'STB-FT-0091823',
    receiptNumber: 'MARS-RCT-884923',
    recordedBy: 'Dr. Michael Ssempa (Owner)',
    notes: 'Stanbic Direct Electronic Funds Transfer',
    date: '2026-08-05',
    paymentTimestamp: Date.now() - 2 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 2 * 86400000,
  },
  {
    id: 'pay-004',
    tenantId: 'ten-5',
    propertyId: 'prop-1',
    unitId: 'unit-104',
    tenantName: 'Brian Kintu',
    unitName: 'Unit 104',
    propertyName: 'Kampala Apartments',
    amount: 600000,
    currency: 'UGX',
    paymentMethod: 'Mobile Money (MTN)',
    paymentStatus: 'SUCCESSFUL',
    externalReference: 'MTN-UG-7711203',
    receiptNumber: 'MARS-RCT-884924',
    recordedBy: 'Peter Ssekandi (Caretaker)',
    notes: 'Partial rent installment; UGX 600,000 remaining',
    date: '2026-08-06',
    paymentTimestamp: Date.now() - 1 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 1 * 86400000,
  },
];

export const INITIAL_EXPENSES: ExpenseEntity[] = [
  {
    id: 'exp-001',
    propertyId: 'prop-1',
    propertyName: 'Kampala Apartments',
    description: 'Peter Ssekandi - Caretaker monthly wage',
    amount: 400000,
    currency: 'UGX',
    category: 'Caretaker Wage',
    recordedBy: 'Dr. Michael Ssempa (Owner)',
    status: 'APPROVED',
    date: '2026-08-01',
    expenseTimestamp: Date.now() - 6 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 6 * 86400000,
  },
  {
    id: 'exp-002',
    propertyId: 'prop-1',
    propertyName: 'Kampala Apartments',
    description: 'NWSC National Water Utility common supply',
    amount: 280000,
    currency: 'UGX',
    category: 'Utilities',
    recordedBy: 'Peter Ssekandi (Caretaker)',
    status: 'APPROVED',
    date: '2026-08-03',
    expenseTimestamp: Date.now() - 4 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 4 * 86400000,
  },
  {
    id: 'exp-003',
    propertyId: 'prop-2',
    propertyName: 'Entebbe Heights',
    description: 'Umeme Yaka Electricity tokens for security lights',
    amount: 190000,
    currency: 'UGX',
    category: 'Utilities',
    recordedBy: 'Peter Ssekandi (Caretaker)',
    status: 'APPROVED',
    date: '2026-08-04',
    expenseTimestamp: Date.now() - 3 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'exp-004',
    propertyId: 'prop-1',
    propertyName: 'Kampala Apartments',
    description: 'Plumbing leak replacement & copper pipe joints Unit 102',
    amount: 150000,
    currency: 'UGX',
    category: 'Repairs',
    recordedBy: 'Peter Ssekandi (Caretaker)',
    status: 'APPROVED',
    date: '2026-08-05',
    expenseTimestamp: Date.now() - 2 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 2 * 86400000,
  },
  {
    id: 'exp-005',
    propertyId: 'prop-3',
    propertyName: 'Jinja View Residencies',
    description: 'Night security guard service August contract',
    amount: 350000,
    currency: 'UGX',
    category: 'Security',
    recordedBy: 'Dr. Michael Ssempa (Owner)',
    status: 'APPROVED',
    date: '2026-08-02',
    expenseTimestamp: Date.now() - 5 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 5 * 86400000,
  },
];

export const INITIAL_MAINTENANCE: MaintenanceEntity[] = [
  {
    id: 'maint-001',
    propertyId: 'prop-1',
    propertyName: 'Kampala Apartments',
    unitId: 'unit-102',
    unitName: 'Unit 102',
    tenantName: 'Sarah Namubiru',
    issue: 'Leaking kitchen sink valve & drain siphon clogging',
    priority: 'HIGH',
    status: 'In Progress',
    assignedProviderId: 'sp-1',
    assignedProviderName: 'Alex Kato (Plumber)',
    estimatedCost: 150000,
    actualCost: 150000,
    date: '2026-08-04',
    reportedTimestamp: Date.now() - 3 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'maint-002',
    propertyId: 'prop-2',
    propertyName: 'Entebbe Heights',
    unitId: 'unit-gate',
    unitName: 'Main Compound Gate',
    tenantName: 'David Ochieng',
    issue: 'Automated sliding gate sensor misaligned & remote receiver faulty',
    priority: 'MEDIUM',
    status: 'Pending',
    assignedProviderId: 'sp-2',
    assignedProviderName: 'Sam Ssebaggala (Electrician)',
    estimatedCost: 85000,
    actualCost: 0,
    date: '2026-08-05',
    reportedTimestamp: Date.now() - 2 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 2 * 86400000,
  },
  {
    id: 'maint-003',
    propertyId: 'prop-3',
    propertyName: 'Jinja View Residencies',
    unitId: 'unit-301',
    unitName: 'Unit 301',
    tenantName: 'Grace Akello',
    issue: 'Bathroom water heater circuit breaker tripping intermittently',
    priority: 'URGENT',
    status: 'Resolved',
    assignedProviderId: 'sp-2',
    assignedProviderName: 'Sam Ssebaggala (Electrician)',
    estimatedCost: 120000,
    actualCost: 110000,
    date: '2026-08-03',
    reportedTimestamp: Date.now() - 4 * 86400000,
    syncStatus: 'SYNCED',
    createdAt: Date.now() - 4 * 86400000,
  },
];

export const INITIAL_SERVICE_PROVIDERS: ServiceProviderEntity[] = [
  {
    id: 'sp-1',
    name: 'Alex Kato',
    serviceType: 'Plumbing',
    phone: '0774556677',
    rate: 'UGX 60,000 / visit',
    rating: 4.9,
    status: 'Available',
    assignedProperty: 'Kampala Apartments',
    isVerified: true,
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: 'sp-2',
    name: 'Sam Ssebaggala',
    serviceType: 'Electrical',
    phone: '0788112233',
    rate: 'UGX 75,000 / visit',
    rating: 4.8,
    status: 'On Job',
    assignedProperty: 'Entebbe Heights',
    isVerified: true,
    createdAt: Date.now() - 85 * 86400000,
  },
  {
    id: 'sp-3',
    name: 'Securitas Uganda Rapid Response',
    serviceType: 'Security',
    phone: '0703445566',
    rate: 'UGX 350,000 / month',
    rating: 5.0,
    status: 'Available',
    assignedProperty: 'Jinja View Residencies',
    isVerified: true,
    createdAt: Date.now() - 120 * 86400000,
  },
  {
    id: 'sp-4',
    name: 'Kampala Pest & Hygiene Services',
    serviceType: 'Fumigation',
    phone: '0755998877',
    rate: 'UGX 180,000 / quarter',
    rating: 4.7,
    status: 'Available',
    assignedProperty: 'Kampala Apartments',
    isVerified: true,
    createdAt: Date.now() - 60 * 86400000,
  },
];

export const INITIAL_RECURRING_TASKS: RecurringTask[] = [
  {
    id: 'rec-1',
    title: 'Overhead Water Tank Chlorination & Desilting',
    property: 'Kampala Apartments',
    frequency: 'Quarterly',
    nextDueDate: '2026-09-15',
    assignedVendor: 'Alex Kato (Plumber)',
    estimatedCost: 250000,
    category: 'Plumbing',
    status: 'Upcoming',
    lastServiced: '2026-06-15',
  },
  {
    id: 'rec-2',
    title: 'Standby Generator Load & Oil Filter Test',
    property: 'Entebbe Heights',
    frequency: 'Monthly',
    nextDueDate: '2026-09-01',
    assignedVendor: 'Sam Ssebaggala (Electrician)',
    estimatedCost: 180000,
    category: 'Electrical',
    status: 'Upcoming',
    lastServiced: '2026-08-01',
  },
  {
    id: 'rec-3',
    title: 'Perimeter Drainage & Soakaway Fumigation',
    property: 'All Properties',
    frequency: 'Bi-annually',
    nextDueDate: '2026-10-10',
    assignedVendor: 'Kampala Pest Control',
    estimatedCost: 320000,
    category: 'Fumigation',
    status: 'Upcoming',
    lastServiced: '2026-04-10',
  },
];

export const INITIAL_AUDIT_TRAIL: AuditEventEntity[] = [
  {
    id: 'audit-001',
    actorUserId: 'user-landlord-1',
    actorName: 'Dr. Michael Ssempa (Owner)',
    eventType: 'LOGIN',
    resourceType: 'AUTH',
    resourceId: 'user-landlord-1',
    details: 'Logged into MARS Cashflow web session via Landlord Master Workspace',
    timestamp: Date.now() - 7200000,
  },
  {
    id: 'audit-002',
    actorUserId: 'user-caretaker-1',
    actorName: 'Peter Ssekandi (Caretaker)',
    eventType: 'PAYMENT_RECORDED',
    resourceType: 'PAYMENT',
    resourceId: 'pay-001',
    details: 'Recorded verified rent payment UGX 1,200,000 for John Mukasa (Unit 101) via MTN Mobile Money. Receipt MARS-RCT-884921 generated.',
    timestamp: Date.now() - 5 * 86400000,
  },
  {
    id: 'audit-003',
    actorUserId: 'user-caretaker-1',
    actorName: 'Peter Ssekandi (Caretaker)',
    eventType: 'EXPENSE_CREATED',
    resourceType: 'EXPENSE',
    resourceId: 'exp-004',
    details: 'Logged maintenance expense UGX 150,000 for plumbing pipe replacements at Kampala Apartments Unit 102.',
    timestamp: Date.now() - 2 * 86400000,
  },
  {
    id: 'audit-004',
    actorUserId: 'user-system',
    actorName: 'MARS Sync Engine',
    eventType: 'SYNC_EXECUTED',
    resourceType: 'SYSTEM',
    resourceId: 'sync-cloud-01',
    details: 'Cloud database snapshot and offline ledger reconciliation completed successfully.',
    timestamp: Date.now() - 1800000,
  },
];
