/**
 * Cryptographic Utility for MARS Cashflow & MARS Corporation Platform
 * 
 * Replaces insecure Math.random() with cryptographically strong pseudo-random
 * numbers generated by the browser's native Crypto API (crypto.getRandomValues / crypto.randomUUID).
 */

export function generateSecureToken(prefix: string = 'inv', byteLength: number = 24): string {
  if (typeof window !== 'undefined' && window.crypto && window.crypto.getRandomValues) {
    const bytes = new Uint8Array(byteLength);
    window.crypto.getRandomValues(bytes);
    const hex = Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
    return `${prefix}_${Date.now()}_${hex}`;
  }
  // Fallback if in Node.js environment
  try {
    const nodeCrypto = require('crypto');
    return `${prefix}_${Date.now()}_${nodeCrypto.randomBytes(byteLength).toString('hex')}`;
  } catch {
    const ts = Date.now().toString(36);
    return `${prefix}_${ts}_${(Math.random() * 1e16).toString(36)}`;
  }
}

export function generateSecureId(prefix: string): string {
  if (typeof window !== 'undefined' && window.crypto) {
    if (typeof window.crypto.randomUUID === 'function') {
      return `${prefix}-${window.crypto.randomUUID()}`;
    }
    const bytes = new Uint8Array(8);
    window.crypto.getRandomValues(bytes);
    const hex = Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
    return `${prefix}-${Date.now()}-${hex}`;
  }
  return `${prefix}-${Date.now()}`;
}

export function generateSecureReceiptNumber(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  
  let randomSegment = '';
  if (typeof window !== 'undefined' && window.crypto && window.crypto.getRandomValues) {
    const bytes = new Uint8Array(4);
    window.crypto.getRandomValues(bytes);
    const num = ((bytes[0] << 24) | (bytes[1] << 16) | (bytes[2] << 8) | bytes[3]) >>> 0;
    randomSegment = String(100000 + (num % 900000));
  } else {
    randomSegment = String(Math.floor(100000 + Math.random() * 900000));
  }

  return `MARS-RCT-${year}${month}-${randomSegment}`;
}

export function generateSecureTicketNumber(): string {
  let randomSegment = '';
  if (typeof window !== 'undefined' && window.crypto && window.crypto.getRandomValues) {
    const bytes = new Uint8Array(3);
    window.crypto.getRandomValues(bytes);
    const num = ((bytes[0] << 16) | (bytes[1] << 8) | bytes[2]) >>> 0;
    randomSegment = String(10000 + (num % 90000));
  } else {
    randomSegment = String(Math.floor(10000 + Math.random() * 90000));
  }

  return `MPU-TK-${randomSegment}`;
}
