import { ProductRegistryEntity, PlatformSubscriptionTierEntity, ProductId } from '../types';

export const MARS_CORPORATION_INFO = {
  name: 'MARS CORPORATION',
  headquarters: 'Kampala, Uganda / Global HQ',
  registrationNumber: 'MARS-CORP-UG-2026-001',
  mission: 'To build modern enterprise platforms, operating systems and sovereign real estate infrastructure across East Africa.',
  supportEmail: 'corporate@marscorporation.com',
  portalUrl: 'https://hq.marscorporation.com',
};

export const INITIAL_REGISTERED_PRODUCTS: ProductRegistryEntity[] = [
  {
    id: 'MARS_CASHFLOW',
    name: 'MARS Cashflow',
    tagline: 'Rental Property Operating System & Sovereign Real Estate Ledger',
    category: 'FINANCE',
    status: 'ACTIVE',
    version: 'v2.4.0-prod',
    customerRoles: ['LANDLORD', 'MANAGER', 'TENANT'],
    icon: '💰',
    description:
      'The flagship customer-facing property cashflow engine for landlords, caretakers, and tenants across Uganda. Enforces strict double-entry ledgering, automated rent arrears tracking, and expense auditing.',
    featureFlags: {
      double_entry_ledger: true,
      uganda_mobile_money_prep: true,
      tenant_sms_reminders: true,
      pdf_reports_generation: true,
      real_time_firestore_sync: true,
      maintenance_tickets: true,
    },
    subscriptionTiers: ['STARTER', 'GROWTH', 'ENTERPRISE'],
    stats: {
      activeWorkspaces: 0,
      totalUsers: 0,
      monthlyThroughputUgx: 0,
    },
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    id: 'MARS_PROPERTIES',
    name: 'MARS Properties',
    tagline: 'Verified Real Estate Marketplace, Title Registry & Commercial Asset Management',
    category: 'REAL_ESTATE',
    status: 'BETA',
    version: 'v1.1.0-beta',
    customerRoles: ['PROPERTY_SELLER', 'BUYER', 'VALUER', 'ESTATE_AGENT'],
    icon: '🏢',
    description:
      'Institutional property asset management, verified land and commercial title registry, and direct investor transaction gateway for vetted real estate portfolios in East Africa.',
    featureFlags: {
      verified_title_deeds: true,
      escrow_settlement: false,
      commercial_listings: true,
      virtual_property_tours: true,
    },
    subscriptionTiers: ['GROWTH', 'ENTERPRISE'],
    stats: {
      activeWorkspaces: 0,
      totalUsers: 0,
      monthlyThroughputUgx: 0,
    },
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    id: 'MARS_URBAN_SERVICES',
    name: 'MARS Urban Services',
    tagline: 'Smart Municipal Utilities, Waste Logistics & Metering Infrastructure',
    category: 'UTILITIES',
    status: 'IN_DEVELOPMENT',
    version: 'v0.8.0-dev',
    customerRoles: ['MUNICIPAL_AGENT', 'UTILITY_VENDOR', 'CONSUMER'],
    icon: '⚡',
    description:
      'Next-generation smart metering, prepaid sub-metering token distribution, automated water/power billing, and urban municipal service coordination for residential clusters.',
    featureFlags: {
      submeter_token_generation: true,
      water_grid_monitoring: false,
      automated_disconnection_relay: false,
    },
    subscriptionTiers: ['ENTERPRISE', 'CUSTOM'],
    stats: {
      activeWorkspaces: 0,
      totalUsers: 0,
      monthlyThroughputUgx: 0,
    },
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    id: 'MARS_PROJECTS',
    name: 'MARS Projects',
    tagline: 'Capital Works, Contractor Dispatch, Renovation & Engineering Oversight',
    category: 'ENGINEERING',
    status: 'ACTIVE',
    version: 'v2.1.0-prod',
    customerRoles: ['GENERAL_CONTRACTOR', 'SITE_ENGINEER', 'PROJECT_OWNER'],
    icon: '🏗️',
    description:
      'Capital works engineering, structural renovation oversight, verified vendor dispatch, and milestone-based construction escrow for large property portfolios.',
    featureFlags: {
      contractor_vetting: true,
      milestone_inspections: true,
      bill_of_quantities_parser: true,
      materials_procurement: true,
    },
    subscriptionTiers: ['GROWTH', 'ENTERPRISE'],
    stats: {
      activeWorkspaces: 0,
      totalUsers: 0,
      monthlyThroughputUgx: 0,
    },
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
];

export const INITIAL_SUBSCRIPTION_TIERS: PlatformSubscriptionTierEntity[] = [
  {
    id: 'tier_starter_cashflow',
    productId: 'MARS_CASHFLOW',
    name: 'Starter Portfolio',
    code: 'STARTER',
    priceUgxMonthly: 50000,
    priceUgxAnnual: 500000,
    maxProperties: 2,
    maxUnits: 20,
    features: [
      'Double-entry rent ledgering',
      'Arrears & debt management',
      'PDF rent receipt generation',
      'Local offline-first database',
      'Single caretaker seat',
    ],
    status: 'ACTIVE',
    createdAt: Date.now() - 100 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'tier_growth_cashflow',
    productId: 'MARS_CASHFLOW',
    name: 'Growth Estate',
    code: 'GROWTH',
    priceUgxMonthly: 150000,
    priceUgxAnnual: 1500000,
    maxProperties: 10,
    maxUnits: 150,
    features: [
      'All Starter features',
      'Multi-manager access control',
      'Direct SMS tenant reminders',
      'Advanced income/expense charts',
      'Bank statement & mobile money reconciliation prep',
      'Priority support',
    ],
    status: 'ACTIVE',
    createdAt: Date.now() - 100 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'tier_enterprise_cashflow',
    productId: 'MARS_CASHFLOW',
    name: 'Enterprise Commercial',
    code: 'ENTERPRISE',
    priceUgxMonthly: 450000,
    priceUgxAnnual: 4500000,
    maxProperties: 50,
    maxUnits: 1000,
    features: [
      'Unlimited properties & units',
      'Custom manager roles & expense limits',
      'MARS Projects Uganda integration for capital works',
      'Google Drive automatic encrypted backups',
      'Dedicated compliance manager & URA tax summaries',
      '24/7 SLA emergency dispatch',
    ],
    status: 'ACTIVE',
    createdAt: Date.now() - 100 * 24 * 60 * 60 * 1000,
  },
];
